### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by Andrei270796** [Agantor/viewerbot#32] opened 2021-03-14 10:13 UTC
Hello, I read then twitch close that backdoor,innit?

**Comment by Agantor** [comment] 2021-07-31 07:47
[iLoooordFx](https://github.com/iLoooordFx) made an update. Check if it works now. If so, I will close the error. Thanks

**Comment by Agantor** [comment] 2021-07-31 08:07
Duplicate of #34

**Closed by Agantor** 2021-07-31 08:07 UTC
