### ISSUE TITLE
ModuleNotFoundError: No module named 'requests' (I have already tried pip install)

### ISSUE THREAD

**Issue by SnailS0me** [Agantor/viewerbot#14] opened 2020-04-28 20:07 UTC

**Comment by Mhelendur** [comment] 2020-05-08 08:30
have you try with python 3 ?

**Comment by SnailS0me** [comment] 2020-05-10 23:08
yep

**Comment by SnailS0me** [comment] 2020-05-10 23:09
oh what am i saying, i got it to work but when i enter the channel URL and
so everything i dont get any viewers?

**Comment by Agantor** [comment] 2021-07-31 07:54
Duplicate of #34

**Closed by Agantor** 2021-07-31 07:54 UTC
