### ISSUE TITLE
Unable to get URL

### ISSUE THREAD

**Issue by Motioncapture21** [Agantor/viewerbot#3] opened 2019-07-31 17:30 UTC
Any working fixes for the Wasnt able to get url error?
Have all the requirements, where does it say "RANDOM CHANNEL".

I have my url put in all the "url" inside the scrip, do I need to put it somewhere else.

**Comment by Rismose** [comment] 2020-10-30 15:46
For anyone wanting help further on this issue, dm me on discord: Rismose#0079

**Comment by Agantor** [comment] 2021-07-31 07:56
Duplicate of #34

**Closed by Agantor** 2021-07-31 07:56 UTC
