### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by danicr-14** [Agantor/viewerbot#21] opened 2020-07-11 23:16 UTC
Hi, I'm a beginner in python but I would like to set this bot for my channel I need views for reach the partner, any can help me setting up this from the beginning? Thanks a lot

**Comment by schrotle** [comment] 2021-01-14 19:41
Not working anymore.

**Comment by Agantor** [comment] 2021-07-31 07:59
Duplicate of #34

**Closed by Agantor** 2021-07-31 07:59 UTC
