### ISSUE TITLE
Erro when running the script

### ISSUE THREAD

**Issue by lvp11** [Agantor/viewerbot#16] opened 2020-05-14 04:52 UTC
Hey!
I`m getting this error:

EXCEPTION IN (threads_viewer.py, LINE 114 "threaded = Thread(target=open_url, args=(all_proxies[random.randint(0, len(all_proxies))],))"): list index out of range
Whats the problem?

Thanks.

**Comment by brunomaffei** [comment] 2020-05-17 00:30
im getting this error too, if someone get the fix solution let us know

**Comment by tidre** [comment] 2020-05-17 15:36
In line 114: 
threaded = Thread(target=open_url, args=(all_proxies[random.randint(0, len(all_proxies))],))

Change to:
threaded = Thread(target=open_url, args=(all_proxies[random.randint(0, len(all_proxies)-1)],))

**Comment by brunomaffei** [comment] 2020-05-17 16:23
@tidre can u give me some advices too?

**Comment by brunomaffei** [comment] 2020-05-17 16:31
"************* Connection Error! *************"
Still show this error too

**Comment by lvp11** [comment] 2020-05-18 00:02
I`m getting this:

`************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
Wasnt able to get url
************* Connection Error! *************
************* Connection Error! *************
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
Wasnt able to get url
************* Connection Error! *************
EXCEPTION IN (threads_viewer.py, LINE 116 "threaded.start()"):`

**Comment by tofixtech** [comment] 2020-05-18 00:07
This error is problem in lib livestreamer, there was probably some change in the twitch api, I'm trying to resolve.

**Comment by brunomaffei** [comment] 2020-05-18 00:12
@tofixtech yes I think the api has changed. So let me know when u get done with that, i'm looking at api but i cant find some solution yet

**Comment by lvp11** [comment] 2020-05-20 22:44
Hey!
Any news on this? =D

**Comment by ZeWhiteHatHacker** [comment] 2020-05-29 22:29
Anyone know how to fix the 
************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url Wasnt able to get url ************* Connection Error! ************* ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url ************* Connection Error! ************* Wasnt able to get url Wasnt able to get url ************* Connection Error! ************* *************
Error?

**Comment by Z3tt0** [comment] 2020-06-12 09:59
Looks like the new API works like this
`POST https://id.twitch.tv/oauth2/token?client_id=<id>&client_secret=<secret>&grant_type=client_credentials`
-> returns <Bearer code>
```
GET https://api.twitch.tv/helix/users?login=<channel>
[
	{
		"key": "Authorization",
		"value": "Bearer <Bearer code>",
		"description": ""
	},
	{
		"key": "Client-ID",
		"value": "<id>",
		"description": ""
	},
	{
		"key": "Client-Secret",
		"value": "<secret>",
		"description": ""
	}
]
```

**Comment by franco9652** [comment] 2020-06-13 01:37
> Parece que la nueva API v5 "Helix" funciona así:
> `POST https://id.twitch.tv/oauth2/token?client_id=<id>&grant_type=client_credentials`
> -> devuelve`<Bearer code>`
> 
> ```
> GET https://api.twitch.tv/helix/users?login=<channel>
> [
> 	{
> 		"key": "Authorization",
> 		"value": "Bearer <Bearer code>"
> 	},
> 	{
> 		"key": "Client-ID",
> 		"value": "<id>"
> 	},
> ]
> ```


would I have to create a new script? or do I already put it in the code?

**Comment by Z3tt0** [comment] 2020-06-14 06:25
> > Parece que la nueva API v5 "Helix" funciona así:
> > `POST https://id.twitch.tv/oauth2/token?client_id=<id>&grant_type=client_credentials`
> > -> devuelve`<Bearer code>`
> > ```
> > GET https://api.twitch.tv/helix/users?login=<channel>
> > [
> > 	{
> > 		"key": "Authorization",
> > 		"value": "Bearer <Bearer code>"
> > 	},
> > 	{
> > 		"key": "Client-ID",
> > 		"value": "<id>"
> > 	},
> > ]
> > ```
> 
> would I have to create a new script? or do I already put it in the code?

I'm not sure. I've tried to adapt the script, but not viewer was added.
My knowledge is too small, sorry.

**Comment by Crazy-Spy** [comment] 2020-08-05 21:39
So.. no luck with that? I'm also getting this connection error... trying with one single threat... 

Tried a new proxy list as well... 

No progress so far...

I don't have knowledge on Python... I wish I had.. to assist on this.

**Comment by maduzy** [comment] 2020-10-11 19:18
Change client-id to 'jzkbprff40iqj646a697cyrvl0zt2m6' in session options in `threads_viewer.py`.
`session.set_option("http-headers", {'User-Agent': ua.random, "Client-ID": "jzkbprff40iqj646a697cyrvl0zt2m6"})`

**Comment by Agantor** [comment] 2021-07-31 07:58
Duplicate of #34

**Closed by Agantor** 2021-07-31 07:58 UTC
